# config.nim - Template. This file is OVERWRITTEN by the builder at compile time.
# Do not edit this file manually - edit builder.py instead.
const
  AgentUUID* = "00000000-0000-0000-0000-000000000000"
  C2BaseUrl* = "http://127.0.0.1:80"
  C2Endpoint* = "/"
  WsHost* = "127.0.0.1"
  WsPort* = 7444
  WsPath* = "ws"
  SleepInterval* = 10
  JitterPercent* = 0
  KillDate* = ""
  UserAgent* = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  AesPsk* = ""
  UsePsk* = true
  DebugMode* = false
